### ISSUE TITLE
Prepended space character to first line of _Species.csv throws KeyError when running do.GenChem

### ISSUE THREAD

**Issue by Micpri** [metno/genchem#12]
Hi

I am currently playing/testing how to introduce an extra mechanisms e.g., in /extra_mechanisms/PAH/ . I have a PAH_Species.csv file and an PAH_Reactions.txt file:

PAH_Species.csv
```Nap,1,C10H8,xx,xx,xx,xx,! Assume all gas phase
BaP,1,C20H12,xx,xx,xx,xx! Assume all particle phase```

PAH_Reactions.txt
```rcemis(HCHO,KDIM)      : = Nap ;
2.16E-11               : Nap + OH = ;
2.00E-19               : Nap + O3 = ;```

Running the following command gives the error: 
```./do.GenChem -b EmChem19a -e PAH```

```[II]   Line   467: RCEMIS(HCHO,KDIM)      : = NAP
[CC]     Traceback (most recent call last):
[CC]       File "/home/user/Code/genchem/chem/scripts/GenChem.py", line 1780, in <module>
[CC]         run_genchem(' '.join(sys.argv[1:]))
[CC]       File "/home/user/Code/genchem/chem/scripts/GenChem.py", line 1732, in run_genchem
[CC]         reactions_reader.read(f, f2)
[CC]       File "/home/user/Code/genchem/chem/scripts/GenChem.py", line 666, in read
[CC]         self.scheme.add_reaction(self._read_reaction(line, log_reac))
[CC]       File "/home/user/Code/genchem/chem/scripts/GenChem.py", line 687, in _read_reaction
[CC]         rhs = [self._read_reaction_term(_) for _ in split(rhs, '+')]
[CC]       File "/home/user/Code/genchem/chem/scripts/GenChem.py", line 687, in <listcomp>
[CC]         rhs = [self._read_reaction_term(_) for _ in split(rhs, '+')]
[CC]       File "/home/user/Code/genchem/chem/scripts/GenChem.py", line 761, in _read_reaction_term
[CC]         species = self.scheme.find_species(species).name
[CC]       File "/home/user/Code/genchem/chem/scripts/GenChem.py", line 361, in find_species
[CC]         return self._species_nocase[name.upper()]
[CC]     KeyError: 'NAP'
DS TMP2```

If I comment out all lines in the _Reactions.txt and run again, everything runs as it should:
  PAH_Reactions.txt
```*rcemis(HCHO,KDIM)      : = Nap ;
*2.16E-11               : Nap + OH = ;
*2.00E-19               : Nap + O3 = ;```

The prod/loss files list output to terminal reveals that the species name from the first line of the PAH_Species.csv file is prepended with a space, meaning it is not read properly and so throws the key error. This doesn't happen with the second line (BaP).

```[II]   SPEC SO2         : nprod= 1, nloss= 0
[II]   SPEC  ﻿Nap        : nprod= 0, nloss= 0
[II]   SPEC BaP         : nprod= 0, nloss= 0
[II]   SPEC SO4         : nprod= 1, nloss= 0
[II]   SPEC NH3         : nprod= 1, nloss= 0```

One work round is to put a dummy line in the first line of the _Species.csv

PAH_Species.csv
```Line1inSpecies.csv,1,,,,
Nap,1,C10H8,xx,xx,xx,xx,! Assume all gas phase
BaP,1,C20H12,xx,xx,xx,xx! Assume all particle phase```

which then shows up in the prod/loss files list

```[II]   SPEC SO2         : nprod= 1, nloss= 0
[II]   SPEC  ﻿Line1inSpecies.csv: nprod= 0, nloss= 0
[II]   SPEC Nap         : nprod= 1, nloss= 2
[II]   SPEC BaP         : nprod= 0, nloss= 0
[II]   SPEC SO4         : nprod= 1, nloss= 0```

**Comment by Micpri** [comment]
Ok I copied and edited a pre-existing folder/structure from the extra_mechanisms directory and now this error has stopped. It must have something to do with how my text editor is saving the file I am writing.

**Comment by mifads** [comment]
Sorry about lack of response. I didn't have notification turned on, and wasn't watching the site. Anyway, good you solved your problem!
